export const homeData = [
  {
    id: 1,
    name: "Metallica",
    desc: "Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist and guitarist James Hetfield and drummer Lars Ulrich, and has been based in San Francisco for most of its career.",
    genres: "rock",
    cover: "../images/p.jpg",
    date: "20-08-2023",
  },
  {
    id: 2,
    name: "Hamlet",
    desc: "Hamlet feigns madness and seeks revenge. His uncle, fearing for his life, also devises plots to kill Hamlet. The play ends with a duel, during which the King, Queen, Hamlet's opponent and Hamlet himself are all killed. ",
    genres: "Theatre",
    cover: "../images/m.jpg",
    date: "10-06-2023",
  },
  {
    id: 3,
    name: "Lake swan",
    desc: "Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist and guitarist James Hetfield and drummer Lars Ulrich, and has been based in San Francisco for most of its career.",
    genres: "theatre",
    cover: "../images/r.jpg",
    date: "20-06-2023",
  },
  {
    id: 4,
    name: "It",
    desc: "the film tells the story of The Losers' Club, a group of seven outcast children who are terrorized by the eponymous being which emerges from the sewer, only to face their own personal demons in the process.",
    genres: "Cinema",
    cover: "../images/l.jpg",
    date: "12-08-2023",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/a1.jpg",
    place:"NYC, Webster Hall",
    name: "The beatls",
    date: "13-AUG-2023",
    prix:"25$",
  },
  {
    id: 2,
    cover: "../images/upcome/a2.jpg",
    place:"Marbella, Starlite",
    name: "Metallica",
    date: "03-JUL-2023",
    prix:"70$",
  },
  {
    id: 3,
    cover: "../images/upcome/a4.jpg",
    place:"London, Kensington Gore",
    name: "The weekend",
    date: "30-JUL-2023",
    prix:"20$",
  },
  {
    id: 4,
    cover: "../images/upcome/a5.jpg",
    place:"Miami, Sit Back",
    name: "the neighbourhood",
    date: "22-SEP-2023",
    prix:"800$",
  },
  {
    id: 5,
    cover: "../images/upcome/a3.jpg",
    place:"NYC, Brooklyn Steel",
    name: "Arctic Monkeys",
    date: "31-DEC-2023",
    prix:"100$",
  },
]
export const upcome1 = [
  {
    id: 1,
    cover: "../images/upcome/p1.jpg",
    name: "Phantom of opera",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"50$",
  },
  {
    id: 2,
    cover: "../images/upcome/p2.jpg",
    name: "Alladin",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"99$",
  },
  {
    id: 3,
    cover: "../images/upcome/p3.jpg",
    name: "Titanic",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"85$",
  },
  {
    id: 4,
    cover: "../images/upcome/p4.jpg",
    name: "Romeo Julliet",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"90$",
  },
  {
    id: 5,
    cover: "../images/upcome/p5.jpg",
    name: "Cinderella",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"100$",
  },
]


export const upcome2 = [
  {
    id: 4,
    cover: "../images/upcome/c1.jpg",
    name: "Shtter islan",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"80$",
  },
  {
    id: 5,
    cover: "../images/upcome/c2.jpg",
    name: "Pulp fiction",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"50$",
  },
  {
    id: 1,
    cover: "../images/upcome/c3.jpg",
    name: "Leon:the pro",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"99$",
  },
  {
    id: 2,
    cover: "../images/upcome/c4.jpg",
    name: "The silence of the lambs",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"75$",
  },
  {
    id: 3,
    cover: "../images/upcome/c5.jpg",
    name: "Seven",
    place:"Miami, Sit Back",
    date: "22-SEP-2023",
    prix:"100$",
  },
]
